redis:
  image: redis:latest

geoip:
  image: allingeek/docker-freegeoip

mysql:
  image: mysql:latest
  volumes: 
    - ~/data/fishbase:/var/lib/mysql
  environment: 
    MYSQL_ROOT_PASSWORD: root

logstash:
  image: pblittle/docker-logstash:latest
  volumes:
    - ~/log/fishbase:/var/log/fishbase
    - ./logstashconf:/opt/logstash/conf.d

api:
  image: ropensci/fishbaseapi:latest
  links:
    - mysql
    - redis
    - geoip
  volumes_from: 
    - logstash

nginx:
  image: nginx:latest
  ports:
   - "80:80"
   - "9292:9292"
   - "9200:9200"
  links:
    - logstash
    - api
  volumes:
    - ~/nginx.conf:/etc/nginx/nginx.conf
    - ~/.htpasswd:/etc/nginx/.htpasswd
    - ~/bundle.crt:/etc/ssl/certs/es.crt
    - ~/es.key:/etc/ssl/private/es.key
